### ISSUE TITLE
Changes and build minified scripts and styles

### ISSUE THREAD

**Issue by martinratinaud** [joashp/material-design-template#10]
Hi and thanks for your work it is really awesome.

I wanted to make some slight changes but can't find a build tool to regenerate `plugin-min.css` and `custom-min.css`. Did you have one or can you tell me how to build those files

Cheers

**Comment by joashp** [comment]
@martinratinaud 
Thanks.
For minification, I use gruntJS - uglify. You could also use https://github.com/mrclay/minify
