### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by danielgomezrico** [joashp/material-design-template#2]
Hi

I liked the theme and the site but it runs really bad in this tests

https://developers.google.com/speed/pagespeed/insights/?hl=es&url=http%3A%2F%2Fjoashpereira.com%2Ftemplates%2Fmaterial_one_pager%2F&tab=mobile

Take a look, maybe can help to make it better!

**Comment by joashp** [comment]
I have minified the the CSS and JS to increase the site performance.
https://github.com/joashp/material-design-template/commit/5354d75472f2491645cb35859ae0ca4b0a7696fc

**Comment by danielgomezrico** [comment]
Cool thanks
