### ISSUE TITLE
menu stays in mobile after choosing

### ISSUE THREAD

**Issue by tleyva** [joashp/material-design-template#6]
when I test the site on my smartphone and I choose for example "team", the nav-bar on the left stays and I need to tap on the content twice. once to remove the menubar and the second time in order to remove the grey overlay.

**Comment by darrellsuggs** [comment]
I'm having the same issue.  It's a great template.  Would like to see this fixed.  Thanks.

**Comment by joashp** [comment]
Issue is resolved. Marking it as closed.

Below pull request merged.
https://github.com/joashp/material-design-template/pull/7
