### ISSUE TITLE
icons are not shown

### ISSUE THREAD

**Issue by tleyva** [joashp/material-design-template#8]
since the last update, the icons for example "<i class="mdi-hardware-desktop-windows"></i>" are not shown anymore or in the footer the social icons.

![icon_issue](https://cloud.githubusercontent.com/assets/1249963/10096368/34cf0644-6371-11e5-8290-225cbcdc5a32.jpg)

**Comment by joashp** [comment]
@tleyva Thanks for notifying.
Have resolved this minor issue in the latest commit.
https://github.com/joashp/material-design-template/commit/9395a5ca1fadeb25693fa907beca2eaaa88075f5
